stages:
  - build
  - test

build-ubuntu20:
  stage: build
  image: ubuntu:20.04
  script:
    - apt-get update && apt-get install -y build-essential qt5-default
    - ./autogen.sh
    - ./configure
    - make -j$(nproc)

build-ubuntu22:
  stage: build
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get install -y build-essential qt5-default
    - ./autogen.sh
    - ./configure
    - make -j$(nproc)

build-ubuntu24:
  stage: build
  image: ubuntu:24.04
  script:
    - apt-get update && apt-get install -y build-essential qt5-default
    - ./autogen.sh
    - ./configure
    - make -j$(nproc)

build-windows10:
  stage: build
  image: mcr.microsoft.com/windows/servercore:ltsc2019
  script:
    - choco install -y qt5
    - ./autogen.sh
    - ./configure
    - make -j$(nproc)

build-windows11:
  stage: build
  image: mcr.microsoft.com/windows/servercore:ltsc2022
  script:
    - choco install -y qt5
    - ./autogen.sh
    - ./configure
    - make -j$(nproc)

build-linux-arm:
  stage: build
  image: arm32v7/ubuntu:20.04
  script:
    - apt-get update && apt-get install -y build-essential qt5-default g++-arm-linux-gnueabihf
    - ./autogen.sh
    - ./configure --host=arm-linux-gnueabihf
    - make -j$(nproc)

build-macos:
  stage: build
  image: cirrusci/macos:latest
  script:
    - brew install qt
    - ./autogen.sh
    - ./configure
    - make -j$(sysctl -n hw.ncpu)