language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - build-essential
            - qt5-default
      script:
        - ./autogen.sh
        - ./configure
        - make -j$(nproc)
        - make check

    - os: linux
      dist: jammy
      addons:
        apt:
          packages:
            - build-essential
            - qt5-default
      script:
        - ./autogen.sh
        - ./configure
        - make -j$(nproc)
        - make check

    - os: linux
      dist: devel
      addons:
        apt:
          packages:
            - build-essential
            - qt5-default
      script:
        - ./autogen.sh
        - ./configure
        - make -j$(nproc)
        - make check

    - os: windows
      script:
        - choco install -y qt5
        - ./autogen.sh
        - ./configure
        - make -j$(nproc)
        - make check

    - os: osx
      osx_image: xcode12.5
      script:
        - brew install qt
        - ./autogen.sh
        - ./configure
        - make -j$(sysctl -n hw.ncpu)
        - make check

    - os: linux
      arch: arm64
      dist: focal
      addons:
        apt:
          packages:
            - build-essential
            - qt5-default
            - g++-arm-linux-gnueabihf
      script:
        - ./autogen.sh
        - ./configure --host=arm-linux-gnueabihf
        - make -j$(nproc)
        - make check