---
name: Gspcoin Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
env:
  COIN_NAME: gspcoin
  BUILD_DIR: gspcoin-build
  COMPRESS_DIR: gspcoin-compress
  TEST_LOG_ARTIFACT_DIR: test-logs
jobs:
  build-ubuntu20:
    name: Build on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential qt5-default
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
      - name: Test
        run: make check

  build-ubuntu22:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential qt5-default
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
      - name: Test
        run: make check

  build-ubuntu24:
    name: Build on Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential qt5-default
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
      - name: Test
        run: make check

  build-windows10:
    name: Build on Windows 10
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: choco install -y qt5
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
      - name: Test
        run: make check

  build-windows11:
    name: Build on Windows 11
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: choco install -y qt5
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
      - name: Test
        run: make check

  build-linux-arm:
    name: Build on Linux ARM
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential qt5-default g++-arm-linux-gnueabihf
      - name: Build
        run: |
          ./autogen.sh
          ./configure --host=arm-linux-gnueabihf
          make -j$(nproc)
      - name: Test
        run: make check

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: brew install qt
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j$(sysctl -n hw.ncpu)
      - name: Test
        run: make check