name: Gspcoin Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  checking-build-version:
    name: Checking Build Versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate version.txt
        run: |
          mkdir -p version
          echo "1.0.0" > version/version.txt
          cat version/version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version/version.txt

  ubuntu-build:
    name: Ubuntu Build Matrix
    needs: checking-build-version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Check if version.txt exists
        run: |
          echo "Listing files in version directory..."
          ls -l version
          if [ -f version/version.txt ]; then
            echo "version.txt exists"
            cat version/version.txt
          else
            echo "version.txt does not exist"
            exit 1
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build application
        run: |
          echo "Building application..."

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build-output
